name: provider_example
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.0.1
  flutter_slidable: ^3.0.0
  http: ^1.1.0
  provider: ^6.0.5
   # UI
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  pinput: ^2.2.16
  dotted_line: ^3.1.0
  syncfusion_flutter_sliders: ^21.1.38
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.7+2
  salomon_bottom_bar: ^3.3.2
  awesome_dialog: ^3.1.0
  google_fonts: ^5.0.0
  fluttertoast: ^8.2.1
  flutter_screenutil: ^5.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  